- hosts: sql2016
  

  vars:
    sqlserver_diagnostic_level_debug: 0
    
    sharepoint_users:
      farm_account:
        username: '{{ account_farm_username }}'
        password: '{{ account_farm_password }}'
        
      web_account:
        Domain:   '{{ account_web_domain | default(inventory_hostname | upper ) }}'
        username: '{{ account_web_username }}'
        password: '{{ account_web_password }}'
        
      service_account:
        Domain:   '{{ account_service_domain | default(inventory_hostname | upper ) }}'
        username: '{{ account_service_username }}'
        password: '{{ account_service_password }}'
    
    
    sqlserver_common:
      sysadmin:
        domain:   '{{ account_sysadmin_domain | default(inventory_hostname | upper ) }}'
        username: '{{ account_sysadmin_username }}'
        password: '{{ account_sysadmin_password }}'
      
      features:
      - SQLENGINE
      - FULLTEXT
#      - RS
#      - AS
#      - IS
      
      instance_name: 'MSSQL'
    
    sqlserver_installer:
      binaries_path: 'F:\'
      download_packages_path:       'D:\SQlServer'
      
      dscResources:
      - xSQLServer
      
      account:
        domain:   '{{ account_installer_domain | default(inventory_hostname | upper ) }}'  
        username: '{{ account_installer_username }}'
        password: '{{ account_installer_password }}'
  tasks:

  - name: Ensure Sql folders for this sample
    win_file:
      path:    '{{ item }}'
      state:   'directory'
    with_items:
    - '{{ sqlserver_installer.download_packages_path }}'
    tags: always

  - name: Create Sharepoint User
    win_user:
      UserName:            '{{ item.username }}'
      Password_username:   '{{ item.Domain }}\{{ item.username }}'
      Password_password:   '{{ item.password }}'
      Ensure: 'Present'
    with_items:
    - '{{ sharepoint_users.service_account }}'
    - '{{ sharepoint_users.web_account }}'
    register: user_status
    tags:
    - user
     
     
  - name: Display user_status
    debug: var=user_status verbosity='{{ sharepoint_diagnostic_level_debug }}'
    tags:
    - user

    
  - block:  
    - name: "win lcm configuration disabled "       
      win_lcm5:
        refresh_mode: 'Disabled'
        
    - name: Download Powershell Modules and DscResources
      win_oneget:
        name: '{{ item }}'
      with_items: '{{ sharepoint_installer.dscResources }}'  

    tags:
    - bootstrap
      
  
#            $Features = "SQLENGINE,FULLTEXT,RS,AS,IS"
#            $Features = "SSMS,ADV_SSMS"
#
#            if($Features -ne "")
#            {
#                xSqlServerSetup ($Node.NodeName + $SQLInstanceName)
#                {
#                    DependsOn = "[WindowsFeature]NET-Framework-Core"
#                    SourcePath = $Node.SourcePath
#                    SetupCredential = $Node.InstallerServiceAccount
#                    InstanceName = $SQLInstanceName
#                    Features = $Features
#                    SQLSysAdminAccounts = $Node.AdminAccount
#                    InstallSharedDir = "C:\Program Files\Microsoft SQL Server"
#                    InstallSharedWOWDir = "C:\Program Files (x86)\Microsoft SQL Server"
#                    InstanceDir = "D:\Program Files\Microsoft SQL Server"
#                    InstallSQLDataDir = "E:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data"
#                    SQLUserDBDir = "F:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data"
#                    SQLUserDBLogDir = "G:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data"
#                    SQLTempDBDir = "H:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data"
#                    SQLTempDBLogDir = "I:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data"
#                    SQLBackupDir = "J:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Data"
#                    ASDataDir = "K:\Program Files\Microsoft SQL Server\MSAS11.MSSQLSERVER\OLAP\Data"
#                    ASLogDir = "L:\Program Files\Microsoft SQL Server\MSAS11.MSSQLSERVER\OLAP\Log"
#                    ASBackupDir = "M:\Program Files\Microsoft SQL Server\MSAS11.MSSQLSERVER\OLAP\Backup"
#                    ASTempDir = "N:\Program Files\Microsoft SQL Server\MSAS11.MSSQLSERVER\OLAP\Temp"
#                    ASConfigDir = "O:\Program Files\Microsoft SQL Server\MSAS11.MSSQLSERVER\OLAP\Config"
#                }
#
  - name:
    win_sqlserversetup:
      SourcePath:               '{{ sqlserver_installer.binaries_path }}'  
      Features:                 '{{ sqlserver_common.features | join(",") }}'
      SetupCredential_username: '{{ sqlserver_installer.account.domain }}\{{ sqlserver_installer.account.username }}'
      SetupCredential_password: '{{ sqlserver_installer.account.password }}'
      SQLSysAdminAccounts:      '{{ sqlserver_common.sysadmin.domain }}\{{ sqlserver_common.sysadmin.username }}'
      InstanceName:             '{{ sqlserver_common.instance_name }}'
    tags:
    - engine    

#    xSqlServerFirewall ($Node.NodeName + $SQLInstanceName)
#    {
#        DependsOn = ("[xSqlServerSetup]" + $Node.NodeName + $SQLInstanceName)
#        SourcePath = $Node.SourcePath
#        InstanceName = $SQLInstanceName
#        Features = $Features
#    }    
  - name:
    win_sqlserverfirewall:
      SourcePath:               '{{ sqlserver_installer.binaries_path }}'  
      Features:                 '{{ sqlserver_common.features | join(",") }}'
      InstanceName:             '{{ sqlserver_common.instance_name }}'
    tags:
    - firewall
      