#- name: "Add users and roles for a Datbase"
- block:
  - name: Ensure Sql Login
    win_dsc:
      resource_name:          SqlServerLogin  
      InstanceName:           '{{ win_mssql_db_instance_name }}'
      ServerName:             '{{ win_mssql_db_server_name }}'
      LoginType:              '{{ item.login_type }}'
      Name:                   >
                              {%- if item.login_type == "WindowsUser"  -%}
                                {{ item.domain | default(win_mssql_db_server_name) }}\{{ item.username }}
                              {%- else -%}
                                {{ item.username }}
                              {%- endif -%}      
    when: item.owner is defined   
    with_items:
    - '{{ win_mssql_db_users }}'      
